name = "pocke-autumn-back"
main = "src/index.ts"
compatibility_date = "2025-12-05"

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "pocke-db"
database_id = "dc58c951-d66f-46c7-ac65-d2be3cac718c"
migrations_dir = "drizzle"

